// Mock data for CarLeads CRM — realistic Indian car dealer leads
// Used during development when Supabase/API is not connected

const now = Date.now();
const min = (m) => new Date(now - m * 60000).toISOString();
const hrs = (h) => new Date(now - h * 3600000).toISOString();

// ============================================
// MOCK DEALER
// ============================================
export const mockDealer = {
  id: 'demo-dealer-1',
  email: 'karan@webiox.in',
  phone: '+919876000001',
  name: 'Karan Patel',
  shop_name: 'Shree Motors',
  city: 'Surat',
  state: 'Gujarat',
  plan: 'pro',
  whatsapp_connected: true,
  instagram_connected: true,
  notification_hot_lead: true,
  notification_daily_summary: true,
  created_at: '2024-06-01T10:00:00Z',
};

// ============================================
// MOCK LEADS — 22 realistic Indian car dealer leads
// ============================================
export const mockLeads = [
  // ── HOT LEADS (Score 7-10) ──
  {
    id: 'lead-001',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Rajesh Patel',
    sender_phone: '+919876543210',
    sender_handle: null,
    message_preview: 'Swift 2019 model hai kya? Budget 4.5 lakh hai, cash payment karunga. Aaj hi dekhne aaunga.',
    ai_score: 10,
    ai_tag: 'hot',
    ai_reason: 'Specific car model, budget stated, cash ready, wants to visit today — highest intent',
    ai_signals: ['specific_model', 'budget_mentioned', 'cash_ready', 'visit_intent', 'urgency'],
    status: 'new',
    is_read: false,
    created_at: min(3),
  },
  {
    id: 'lead-002',
    dealer_id: 'demo-dealer-1',
    platform: 'instagram',
    sender_name: 'Priya Sharma',
    sender_phone: null,
    sender_handle: '@priya.sharma.99',
    message_preview: 'Hi, I am looking for Honda City 2022 diesel variant. My budget is 8-9 lakh. I am from Surat, can visit your showroom tomorrow morning.',
    ai_score: 10,
    ai_tag: 'hot',
    ai_reason: 'Specific model + variant, clear budget range, location match, visit scheduled',
    ai_signals: ['specific_model', 'variant_specified', 'budget_range', 'location_match', 'visit_scheduled'],
    status: 'new',
    is_read: false,
    created_at: min(8),
  },
  {
    id: 'lead-003',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Mehul Shah',
    sender_phone: '+919898123456',
    sender_handle: null,
    message_preview: 'Hyundai Creta 2021 SX model available hai? Finance ho jayega kya? Budget 10 lakh ke aaspass.',
    ai_score: 9,
    ai_tag: 'hot',
    ai_reason: 'Specific model + variant, budget mentioned, asking about finance — serious buyer',
    ai_signals: ['specific_model', 'variant_specified', 'budget_mentioned', 'finance_inquiry'],
    status: 'new',
    is_read: false,
    created_at: min(22),
  },
  {
    id: 'lead-004',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Amit Desai',
    sender_phone: '+919876111222',
    sender_handle: null,
    message_preview: 'Tata Nexon 2020 automatic hai kya? Petrol variant chahiye. 7 lakh tak ka budget hai.',
    ai_score: 8,
    ai_tag: 'hot',
    ai_reason: 'Specific model, variant preference, fuel type, clear budget',
    ai_signals: ['specific_model', 'variant_specified', 'fuel_preference', 'budget_mentioned'],
    status: 'contacted',
    is_read: true,
    created_at: min(45),
  },
  {
    id: 'lead-005',
    dealer_id: 'demo-dealer-1',
    platform: 'instagram',
    sender_name: 'Neha Joshi',
    sender_phone: null,
    sender_handle: '@neha.joshi.cars',
    message_preview: 'I want to buy a Maruti Baleno 2021 or 2022. My budget is around 6 lakh. Can you share some options?',
    ai_score: 8,
    ai_tag: 'hot',
    ai_reason: 'Specific model, year range preference, clear budget, requesting options',
    ai_signals: ['specific_model', 'year_preference', 'budget_mentioned', 'options_requested'],
    status: 'new',
    is_read: false,
    created_at: hrs(1),
  },
  {
    id: 'lead-006',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Vikram Modi',
    sender_phone: '+919825678900',
    sender_handle: null,
    message_preview: 'Bhai i20 2020 model dekhna hai, kal subah aa sakta hu. 5.5 lakh ka budget hai.',
    ai_score: 7,
    ai_tag: 'hot',
    ai_reason: 'Specific model, visit intent for tomorrow, budget stated',
    ai_signals: ['specific_model', 'visit_intent', 'budget_mentioned'],
    status: 'new',
    is_read: false,
    created_at: hrs(1.5),
  },

  // ── WARM LEADS (Score 4-6) ──
  {
    id: 'lead-007',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Ravi Trivedi',
    sender_phone: '+919876222333',
    sender_handle: null,
    message_preview: 'Koi acchi second hand car hai kya? Family ke liye chahiye. Budget thoda flexible hai.',
    ai_score: 6,
    ai_tag: 'warm',
    ai_reason: 'Interested but no specific model, mentions family use — some intent',
    ai_signals: ['general_interest', 'use_case_mentioned', 'flexible_budget'],
    status: 'new',
    is_read: false,
    created_at: hrs(2),
  },
  {
    id: 'lead-008',
    dealer_id: 'demo-dealer-1',
    platform: 'instagram',
    sender_name: 'Ankit Mehta',
    sender_phone: null,
    sender_handle: '@ankit.mehta.07',
    message_preview: 'What SUVs do you have in 8-12 lakh range? Looking for something with good mileage.',
    ai_score: 6,
    ai_tag: 'warm',
    ai_reason: 'Budget range given, vehicle category specified, but no specific model',
    ai_signals: ['category_specified', 'budget_range', 'feature_preference'],
    status: 'new',
    is_read: false,
    created_at: hrs(3),
  },
  {
    id: 'lead-009',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Deepak Soni',
    sender_phone: '+919876333444',
    sender_handle: null,
    message_preview: 'Cars ki list bhejo 5 lakh ke neeche wali',
    ai_score: 5,
    ai_tag: 'warm',
    ai_reason: 'Budget mentioned but very broad request, wants list — exploring stage',
    ai_signals: ['budget_mentioned', 'list_requested'],
    status: 'new',
    is_read: true,
    created_at: hrs(4),
  },
  {
    id: 'lead-010',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Suresh Yadav',
    sender_phone: '+919876444555',
    sender_handle: null,
    message_preview: 'Diesel car chahiye, thoda sasta mein. Kya rate hai?',
    ai_score: 5,
    ai_tag: 'warm',
    ai_reason: 'Fuel preference but no model, wants cheap — vague interest',
    ai_signals: ['fuel_preference', 'price_sensitive'],
    status: 'new',
    is_read: false,
    created_at: hrs(5),
  },
  {
    id: 'lead-011',
    dealer_id: 'demo-dealer-1',
    platform: 'instagram',
    sender_name: 'Pooja Verma',
    sender_phone: null,
    sender_handle: '@pooja.verma.456',
    message_preview: 'Do you have any automatic cars? I am a new driver and want something easy to drive.',
    ai_score: 4,
    ai_tag: 'warm',
    ai_reason: 'Interested but very early stage, no model or budget',
    ai_signals: ['transmission_preference', 'new_driver'],
    status: 'new',
    is_read: false,
    created_at: hrs(6),
  },
  {
    id: 'lead-012',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Hitesh Raval',
    sender_phone: '+919876555666',
    sender_handle: null,
    message_preview: 'Showroom ka address kya hai? Kab tak khula rehta hai?',
    ai_score: 4,
    ai_tag: 'warm',
    ai_reason: 'Asking about showroom visit — could be genuine or just browsing',
    ai_signals: ['location_inquiry', 'timing_inquiry'],
    status: 'contacted',
    is_read: true,
    created_at: hrs(7),
  },

  // ── FAKE / LOW INTENT LEADS (Score 1-3) ──
  {
    id: 'lead-013',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Unknown',
    sender_phone: '+919876666777',
    sender_handle: null,
    message_preview: 'bhai price bata',
    ai_score: 2,
    ai_tag: 'fake',
    ai_reason: 'No model specified, lazy generic query — typical timepass message',
    ai_signals: ['no_model', 'generic_query'],
    status: 'new',
    is_read: false,
    created_at: hrs(2.5),
  },
  {
    id: 'lead-014',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Kiran Solanki',
    sender_phone: '+919876777888',
    sender_handle: null,
    message_preview: 'hello',
    ai_score: 1,
    ai_tag: 'fake',
    ai_reason: 'Single word greeting, zero buying intent',
    ai_signals: ['greeting_only'],
    status: 'new',
    is_read: false,
    created_at: hrs(3),
  },
  {
    id: 'lead-015',
    dealer_id: 'demo-dealer-1',
    platform: 'instagram',
    sender_name: 'random_user_42',
    sender_phone: null,
    sender_handle: '@random_user_42',
    message_preview: '👍',
    ai_score: 1,
    ai_tag: 'fake',
    ai_reason: 'Emoji only, no message content',
    ai_signals: ['emoji_only'],
    status: 'new',
    is_read: false,
    created_at: hrs(4),
  },
  {
    id: 'lead-016',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Manish Thakor',
    sender_phone: '+919876888999',
    sender_handle: null,
    message_preview: 'photo bhejo',
    ai_score: 2,
    ai_tag: 'fake',
    ai_reason: 'Demanding photos without specifying any car — likely browsing',
    ai_signals: ['no_model', 'media_request_only'],
    status: 'new',
    is_read: false,
    created_at: hrs(5),
  },
  {
    id: 'lead-017',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Jignesh Prajapati',
    sender_phone: '+919876999111',
    sender_handle: null,
    message_preview: 'sab se sasta car kaunsi hai?',
    ai_score: 2,
    ai_tag: 'fake',
    ai_reason: 'Only asking for cheapest, no intent to actually buy',
    ai_signals: ['cheapest_query', 'no_budget'],
    status: 'new',
    is_read: true,
    created_at: hrs(8),
  },
  {
    id: 'lead-018',
    dealer_id: 'demo-dealer-1',
    platform: 'instagram',
    sender_name: 'car_lover_007',
    sender_phone: null,
    sender_handle: '@car_lover_007',
    message_preview: 'nice cars bro 🔥🔥',
    ai_score: 1,
    ai_tag: 'fake',
    ai_reason: 'Compliment only, no buying intent',
    ai_signals: ['compliment_only', 'no_intent'],
    status: 'new',
    is_read: false,
    created_at: hrs(10),
  },
  {
    id: 'lead-019',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Bhavesh Gajera',
    sender_phone: '+919825111222',
    sender_handle: null,
    message_preview: 'exchange hota hai kya? meri purani car deni hai',
    ai_score: 3,
    ai_tag: 'fake',
    ai_reason: 'Asking about exchange but no specific car interest mentioned',
    ai_signals: ['exchange_inquiry', 'no_model'],
    status: 'new',
    is_read: false,
    created_at: hrs(12),
  },
  {
    id: 'lead-020',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Chirag Nakum',
    sender_phone: '+919825222333',
    sender_handle: null,
    message_preview: 'loan milega kya? mera cibil score kharab hai',
    ai_score: 3,
    ai_tag: 'fake',
    ai_reason: 'Finance inquiry with bad credit disclosure — unlikely to convert',
    ai_signals: ['finance_inquiry', 'bad_credit'],
    status: 'new',
    is_read: false,
    created_at: hrs(14),
  },
  {
    id: 'lead-021',
    dealer_id: 'demo-dealer-1',
    platform: 'instagram',
    sender_name: 'Kashyap Darji',
    sender_phone: null,
    sender_handle: '@kashyap.darji',
    message_preview: 'Can I get a test drive? I want to try different cars before deciding.',
    ai_score: 3,
    ai_tag: 'fake',
    ai_reason: 'Test drive request without any specific car — browsing behavior',
    ai_signals: ['test_drive_request', 'no_specific_model', 'undecided'],
    status: 'new',
    is_read: false,
    created_at: hrs(18),
  },
  {
    id: 'lead-022',
    dealer_id: 'demo-dealer-1',
    platform: 'whatsapp',
    sender_name: 'Darshan Vaghela',
    sender_phone: '+919825333444',
    sender_handle: null,
    message_preview: 'Bhai tu dealer hai? Mujhe dealer banna hai, kaise start karu?',
    ai_score: 1,
    ai_tag: 'fake',
    ai_reason: 'Not a buyer — asking how to become a dealer',
    ai_signals: ['not_a_buyer', 'business_inquiry'],
    status: 'new',
    is_read: false,
    created_at: hrs(24),
  },
];

// ============================================
// MOCK MESSAGES (conversation threads for first 5 leads)
// ============================================
export const mockMessages = {
  'lead-001': [
    {
      id: 'msg-001-1',
      lead_id: 'lead-001',
      direction: 'inbound',
      message_text: 'Swift 2019 model hai kya? Budget 4.5 lakh hai, cash payment karunga. Aaj hi dekhne aaunga.',
      message_type: 'text',
      created_at: min(3),
    },
  ],
  'lead-002': [
    {
      id: 'msg-002-1',
      lead_id: 'lead-002',
      direction: 'inbound',
      message_text: 'Hi, I am looking for Honda City 2022 diesel variant. My budget is 8-9 lakh. I am from Surat, can visit your showroom tomorrow morning.',
      message_type: 'text',
      created_at: min(8),
    },
  ],
  'lead-003': [
    {
      id: 'msg-003-1',
      lead_id: 'lead-003',
      direction: 'inbound',
      message_text: 'Hyundai Creta 2021 SX model available hai? Finance ho jayega kya? Budget 10 lakh ke aaspass.',
      message_type: 'text',
      created_at: min(22),
    },
  ],
  'lead-004': [
    {
      id: 'msg-004-1',
      lead_id: 'lead-004',
      direction: 'inbound',
      message_text: 'Tata Nexon 2020 automatic hai kya? Petrol variant chahiye. 7 lakh tak ka budget hai.',
      message_type: 'text',
      created_at: min(45),
    },
    {
      id: 'msg-004-2',
      lead_id: 'lead-004',
      direction: 'outbound',
      message_text: 'Hello Amit ji! Yes, we have 2 Nexon 2020 automatic petrol available. One is XZ+ variant in white color, 32,000 km driven at 6.8L. Shall I send photos?',
      message_type: 'text',
      created_at: min(40),
    },
    {
      id: 'msg-004-3',
      lead_id: 'lead-004',
      direction: 'inbound',
      message_text: 'Haan photos bhejo. White wala accha hai. Kal aake dekh lunga.',
      message_type: 'text',
      created_at: min(38),
    },
  ],
  'lead-005': [
    {
      id: 'msg-005-1',
      lead_id: 'lead-005',
      direction: 'inbound',
      message_text: 'I want to buy a Maruti Baleno 2021 or 2022. My budget is around 6 lakh. Can you share some options?',
      message_type: 'text',
      created_at: hrs(1),
    },
  ],
};

// ============================================
// MOCK STATS
// ============================================
export const mockStats = {
  overview: {
    totalLeadsToday: 23,
    hotLeadsToday: 6,
    responseRate: 72,
    fakePercentage: 35,
  },
  byPlatform: [
    { platform: 'WhatsApp', count: 15, color: '#25D366' },
    { platform: 'Instagram', count: 6, color: '#E1306C' },
    { platform: 'Manual', count: 2, color: '#6C5CE7' },
  ],
  scoreDistribution: [
    { range: '9-10', label: 'Super Hot', count: 3, color: '#00D26A' },
    { range: '7-8', label: 'Hot', count: 4, color: '#00B85C' },
    { range: '5-6', label: 'Warm', count: 5, color: '#F5A623' },
    { range: '3-4', label: 'Cool', count: 4, color: '#FF8C42' },
    { range: '1-2', label: 'Fake', count: 6, color: '#FF4757' },
  ],
  weekly: [
    { day: 'Mon', date: '19 May', leads: 18, hot: 4 },
    { day: 'Tue', date: '20 May', leads: 22, hot: 5 },
    { day: 'Wed', date: '21 May', leads: 15, hot: 3 },
    { day: 'Thu', date: '22 May', leads: 28, hot: 7 },
    { day: 'Fri', date: '23 May', leads: 20, hot: 4 },
    { day: 'Sat', date: '24 May', leads: 25, hot: 6 },
    { day: 'Sun', date: '25 May', leads: 12, hot: 2 },
  ],
  recentHotLeads: [], // Will be populated from mockLeads
};

// Helper: get hot leads from mock data
mockStats.recentHotLeads = mockLeads
  .filter((l) => l.ai_tag === 'hot')
  .sort((a, b) => new Date(b.created_at) - new Date(a.created_at))
  .slice(0, 5);

// ============================================
// MOCK NOTIFICATIONS
// ============================================
export const mockNotifications = [
  {
    id: 'notif-001',
    dealer_id: 'demo-dealer-1',
    type: 'hot_lead',
    title: '🔥 Hot Lead!',
    body: 'Rajesh Patel is interested in Swift 2019. Budget: ₹4.5L cash. Reply now!',
    lead_id: 'lead-001',
    is_read: false,
    created_at: min(3),
  },
  {
    id: 'notif-002',
    dealer_id: 'demo-dealer-1',
    type: 'hot_lead',
    title: '🔥 Hot Lead!',
    body: 'Priya Sharma wants Honda City 2022 diesel. Budget: ₹8-9L. Wants to visit tomorrow!',
    lead_id: 'lead-002',
    is_read: false,
    created_at: min(8),
  },
  {
    id: 'notif-003',
    dealer_id: 'demo-dealer-1',
    type: 'follow_up_reminder',
    title: '⏰ Follow Up Reminder',
    body: 'Neha Joshi asked about Maruti Baleno 1 hour ago. No response yet.',
    lead_id: 'lead-005',
    is_read: false,
    created_at: min(30),
  },
  {
    id: 'notif-004',
    dealer_id: 'demo-dealer-1',
    type: 'hot_lead',
    title: '🔥 Hot Lead!',
    body: 'Mehul Shah interested in Hyundai Creta 2021 SX. Budget: ₹10L. Asking about finance.',
    lead_id: 'lead-003',
    is_read: true,
    created_at: min(22),
  },
];
